services:
  db:
    image: postgres:15
    container_name: go_tasks_db
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_tasks_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tasks_db
      SERVER_PORT: 8080
      JWT_SECRET: super_secret_token

volumes:
  pgdata: